# Generated by Django 4.2.2 on 2023-06-10 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('traits', '0001_initial'),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='groups.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='trait',
            field=models.ManyToManyField(related_name='pet', to='traits.trait'),
        ),
    ]
