# Generated by Django 4.2.2 on 2023-06-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_alter_pet_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Not informed', 'Default')], default=('Not informed', 'Default'), max_length=20),
        ),
    ]
