# Generated by Django 4.2.2 on 2023-06-10 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_created_at'),
        ('traits', '0001_initial'),
        ('pets', '0009_alter_pet_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='trait',
        ),
        migrations.AddField(
            model_name='pet',
            name='traits',
            field=models.ManyToManyField(related_name='pets', to='traits.trait'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='groups.group'),
        ),
    ]
