# Generated by Django 4.2.2 on 2023-06-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_remove_pet_trait_pet_traits_alter_pet_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('not_informed', 'Not Informed')], default='not_informed', max_length=20),
        ),
    ]
